before_script:
  - id
  - pwd

stages:
  - build
  - package
  - deploy

build:app:
  stage: build
  script:
    - npm install
    - node_modules/punch/bin/punch g
  artifacts:
    paths:
      - output/

package:archive:
  stage: package
  dependencies:
    - build:app
  only:
    - master
  script:
    - tar cvzf atilla-org.tar.gz output
  artifacts:
    paths:
      - atilla-org.tar.gz

deploy:prod:
  stage: deploy
  dependencies:
    - package:archive
  environment:
    name: production
    url: https://atilla.org
  only:
    - master
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRODUCTION_PRIVATE_KEY")
    - scp atilla-org.tar.gz atilla@webstatic-prod.prod.infra.atilla.org:~/
    - ssh -t atilla@webstatic-prod.prod.infra.atilla.org "tar -xf atilla-org.tar.gz"
