before_script:
  - id
  - pwd

stages:
  - build
  - deploy

build:app:
  stage: build
  script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
    - nvm install v12.16.3
    - npm install
    - node_modules/punch/bin/punch g
  artifacts:
    paths:
      - output/

deploy:prod:
  stage: deploy
  dependencies:
          - build:app
  environment:
    name: production
    url: https://atilla.org
  only:
    - master
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRODUCTION_PRIVATE_KEY")
    - rsync --checksum --recursive --delete --delete-during --itemize-changes --verbose output/ atilla@webstatic-prod.prod.infra.atilla.org:~/website
